import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { fmt, type Prediction, type Relations, type Segment } from "../api";
import { usePlayhead } from "../store";
type Window = {start_ms:number;end_ms:number;wpm?:number;pitch_hz?:number;pitch_std_hz?:number;voiced_fraction?:number};
type Decision = {interval?:{start_ms:number;end_ms:number};start_ms?:number;end_ms?:number;question?:string;answer?:string;decision?:string;reason?:string;quote?:string;rewrite?:string;confidence?:number;status?:string;explanation?:string;suggested_rewrite?:string;preserve?:string[]|string;counter_explanation?:string};
type Data = {duration_ms:number;voice:{status:string;windows:Window[];summary?:Record<string,unknown>};audio:{status:string;rms?:{t_ms:number[];dbfs:(number|null)[]};silence?:{start_ms:number;end_ms:number}[];summary?:Record<string,unknown>;loudness?:{integrated_lufs?:number;lra_lu?:number;true_peak_dbfs?:number;short_term_t_ms?:number[];short_term_lufs?:number[]}};jev?:{status:string;reason?:string;decisions:Decision[]}};
export function useDeepDive(id:string) {return useQuery({queryKey:["deepdive",id],queryFn:async()=>{const r=await fetch("/api/v1/runs/"+id+"/deepdive");if(!r.ok)throw new Error("Direct voice and audio diagnostics unavailable for this run.");return r.json() as Promise<Data>},retry:false});}
const time=(ms:number)=>fmt(ms).replace(/\.\d$/,"");
type Series={name:string;color:string;points:{t:number;v:number}[]};
export function SignalChart({title,description,series,duration,unit,min,max}:{title:string;description:string;series:Series[];duration:number;unit:string;min?:number;max?:number}){
 const {focus,currentMs}=usePlayhead();const values=series.flatMap(s=>s.points).filter(p=>Number.isFinite(p.v));const lo=min??Math.min(0,...values.map(p=>p.v));const hi=Math.max(lo+1,max??Math.max(...values.map(p=>p.v)));const x=(t:number)=>55+t/Math.max(1,duration)*730;const y=(v:number)=>15+(hi-Math.max(lo,Math.min(hi,v)))/(hi-lo)*160;
 return <section className="metric-chart"><h4>{title}</h4><p className="faint">{description}</p>{!values.length?<p className="muted">Unknown — no measured values available.</p>:<><svg viewBox="0 0 800 210" role="img" aria-label={title+", "+unit} onClick={e=>{const r=e.currentTarget.getBoundingClientRect();const t=Math.max(0,Math.min(duration,((e.clientX-r.left)/r.width*800-55)/730*duration));focus({start_ms:Math.round(t),end_ms:Math.min(duration,Math.round(t)+5000)},null)}}>
 {[0,.25,.5,.75,1].map(f=><g key={f}><line x1={55} x2={785} y1={y(lo+(hi-lo)*f)} y2={y(lo+(hi-lo)*f)} stroke="#e5e2dc"/><text x={47} y={y(lo+(hi-lo)*f)+4} textAnchor="end">{(lo+(hi-lo)*f).toFixed(hi>20?0:2)}</text><text x={x(duration*f)} y={200} textAnchor="middle">{time(duration*f)}</text></g>)}
 {series.map(s=><path key={s.name} d={s.points.map((p,i)=>Number.isFinite(p.v)?((i===0||!Number.isFinite(s.points[i-1].v))?"M":"L")+x(p.t)+","+y(p.v):"").join(" ")} stroke={s.color} fill="none" strokeWidth={2} vectorEffect="non-scaling-stroke"/>)}
 <line x1={x(currentMs)} x2={x(currentMs)} y1={15} y2={175} stroke="#a36e14" strokeDasharray="3 3"/></svg><div className="legend">{series.map(s=><span key={s.name}><span className="swatch" style={{background:s.color}}/>{s.name}</span>)}<span className="faint">{unit} · click to seek</span></div></>}</section>;
}
function Summary({data}:{data?:Record<string,unknown>}) {return data?<dl className="deep-summary">{Object.entries(data).filter(([,v])=>typeof v==="string"||typeof v==="number").map(([k,v])=><div key={k}><dt>{k.replace(/_/g," ")}</dt><dd>{typeof v==="number"?v.toFixed(1):String(v)}</dd></div>)}</dl>:null;}
export function WatchCharts({pred,duration}:{pred:Prediction;duration:number}){
 let sum=0;let previous=1;const cumulative=pred.per_second.map(p=>{const q=p as typeof p&{duration_s?:number;end_s?:number;hazard_per_s?:number};const dt=q.duration_s??Math.max(0,Math.min(duration/1000,p.t+1)-p.t);const h=q.hazard_per_s;sum+=typeof h==="number"?(h>1e-12?previous*(-Math.expm1(-h*dt))/h:previous*dt):(previous+p.retention)*.5*dt;previous=p.retention;return {t:(q.end_s??Math.min(duration/1000,p.t+1))*1000,v:sum}});return <div className="deep-grid two"><SignalChart title="Cumulative watch time per starting viewer" description="Area under the assumed retention curve. Final value is scenario average watch duration, not measured watch time." series={[{name:"Assumed watch seconds",color:"#268579",points:cumulative}]} duration={duration} unit="seconds"/><SignalChart title="Viewers remaining per 100 starts" description="Retention expressed as a count; the baseline is an assumption, not channel analytics." series={[{name:"Scenario viewers",color:"#c47b32",points:pred.per_second.map(p=>({t:Math.min(duration,(p.t+1)*1000),v:p.retention*100}))},{name:"Assumed baseline",color:"#89908b",points:pred.per_second.map(p=>({t:Math.min(duration,(p.t+1)*1000),v:p.neutral*100}))}]} duration={duration} unit="viewers/100" min={0} max={100}/></div>;
}
export function DeepDive({runId,section,data,duration,pred,segments,relations}:{runId:string;section:"overview"|"voice"|"audio"|"text";data?:Data;duration:number;pred?:Prediction;segments:Segment[];relations?:Relations}){
 const {focus,selection}=usePlayhead(); const [question,setQuestion]=useState("Does this passage need a rewrite to improve clarity without removing information?"); const [checked,setChecked]=useState<Decision[]|null>(null); const [checkStatus,setCheckStatus]=useState<string|null>(null); const check=useMutation({mutationFn:async()=>{const r=await fetch("/api/v1/runs/"+runId+"/jev-review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question,selection})}); const body=await r.json();if(!r.ok)throw new Error(body.error?.message??body.detail??"Jev check failed");return body as {decisions:Decision[];status?:string;reason?:string}},onSuccess:r=>{setChecked(r.decisions);setCheckStatus((r.status??"unknown")+(r.reason?" — "+r.reason:""))}}); const voice=data?.voice;const audio=data?.audio;const words=segments.reduce((n,s)=>n+s.text.split(/\s+/).filter(Boolean).length,0);const speech=segments.reduce((n,s)=>n+s.interval.end_ms-s.interval.start_ms,0);
 const textFindings=(pred as (Prediction&{analysis?:{findings:Finding[]}})|undefined)?.analysis?.findings??[]; const actionable=(data?.jev?.decisions??[]).filter(d=>["rewrite","shorten"].includes(d.decision??"")); const display=(v:unknown)=>typeof v==="number"?v.toFixed(1):"unknown"; const voiceSeries=(key:keyof Window)=>[{name:key.replace(/_/g," "),color:"#268579",points:(voice?.windows??[]).map(w=>({t:w.start_ms,v:typeof w[key]==="number"?w[key] as number:NaN}))}];
 if(section==="overview")return <div className="deepdive"><div className="deep-heading"><div><h3>Overview</h3><p className="muted">Content, delivery and recording evidence together. Measurements describe this video; scenarios describe assumptions.</p></div><span className="pill uncal">No audience analytics attached</span></div><div className="deep-stats">{[[time(duration),"Video duration"],[time(speech),"Transcript segment coverage"],[words,"Transcript words"],[pred?time(pred.summary.avd_s.central*1000):"Unknown","Assumed average watch time"]].map(([v,k])=><div key={k}><b>{v}</b><span>{k}</span></div>)}</div><div className="deep-grid">{[["Text",textFindings.length+" provisional text candidates. "+(relations?relations.summary.questions+" questions; "+relations.summary.no_callback+" without detected callback.":"Relationships loading.")],["Voice","Speech rate "+display(voice?.summary?.overall_wpm)+" words/min; median pitch "+display(voice?.summary?.median_pitch_hz)+" Hz. Status: "+(voice?.status??"unknown")+". These describe delivery, not engagement."],["Audio",display(audio?.summary?.silence_s)+" seconds of detected silence; "+display(audio?.loudness?.integrated_lufs)+" LUFS integrated loudness; "+display(audio?.summary?.clipping_windows)+" clipped windows. Listen before choosing a correction."]].map(([k,v])=><section className="deep-card" key={k}><h4>{k}</h4><p>{v}</p></section>)}</div><h4>Review priorities across the evidence</h4><p className="faint">{actionable.length} Jev rewrite/shorten choices. These are model judgements, separate from validated findings. Review the passage and preserve its information before editing.</p><div className="rewrite-grid">{textFindings.slice(0,3).map(f=><article className="rewrite-card" key={f.finding_id}><button className="time" onClick={()=>focus({start_ms:f.start_ms,end_ms:f.end_ms},null)}>{time(f.start_ms)}–{time(f.end_ms)}</button><h4>{f.rule_id.replace(/_/g," ")}</h4><p>{f.mechanism}</p><p><b>Review action:</b> {f.suggestion}</p></article>)}{actionable.map((d,i)=><article className="rewrite-card" key={"j"+i}><button className="time" onClick={()=>focus({start_ms:d.start_ms??0,end_ms:d.end_ms??duration},null)}>{time(d.start_ms??0)}–{time(d.end_ms??duration)}</button><h4>Jev: {d.decision} · needs review</h4><p>{d.explanation??d.reason}</p></article>)}</div>{pred&&<WatchCharts pred={pred} duration={duration}/>}</div>;
 if(section==="voice")return <div className="deepdive"><h3>Voice delivery</h3><p className="muted">Direct waveform and aligned-speech measurements. Status: {voice?.status??"unknown"}. Low variation alone is not a reason to rewrite.</p><div className="deep-grid two"><SignalChart title="Speaking rate" description="Aligned words per minute in each window, including pauses. Variation may reflect emphasis or explanation." series={voiceSeries("wpm")} duration={duration} unit="words/min"/><SignalChart title="Pitch contour" description="Estimated fundamental frequency in voiced windows. Missing windows remain unknown." series={voiceSeries("pitch_hz")} duration={duration} unit="Hz"/><SignalChart title="Pitch variation" description="Within-window pitch spread. Compare against the same speaker rather than a universal ideal." series={voiceSeries("pitch_std_hz")} duration={duration} unit="Hz"/><SignalChart title="Voiced coverage" description="Fraction of candidate speech frames with valid pitch estimates; not whole-window speech coverage or a voice-quality score." series={voiceSeries("voiced_fraction")} duration={duration} unit="fraction" min={0} max={1}/></div><Summary data={voice?.summary}/></div>;
 if(section==="audio")return <div className="deepdive"><h3>Audio recording</h3><p className="muted">Direct signal measurements. Status: {audio?.status??"unknown"}. Digital level does not measure enjoyment or intelligibility.</p><SignalChart title="Audio level over time" description="RMS amplitude relative to digital full scale. Silence approaches the floor; 0 dBFS is the digital ceiling." series={[{name:"RMS level",color:"#268579",points:(audio?.rms?.t_ms??[]).map((t,i)=>({t,v:audio?.rms?.dbfs[i]??NaN}))}]} duration={duration} unit="dBFS" min={-80} max={0}/><SignalChart title="Short-term loudness" description="Perceptual loudness measured over short windows. Values are descriptive; no universal correction target is assumed." series={[{name:"Short-term loudness",color:"#7956a5",points:(audio?.loudness?.short_term_t_ms??[]).map((t,i)=>({t,v:audio?.loudness?.short_term_lufs?.[i]??NaN}))}]} duration={duration} unit="LUFS"/><Summary data={audio?.summary}/><Summary data={audio?.loudness as Record<string,unknown>|undefined}/><h4>Detected silence intervals</h4><p className="faint">Pauses may be intentional. Listen to the surrounding section before trimming.</p><div className="interval-list">{(audio?.silence??[]).map((s,i)=><button key={i} onClick={()=>focus(s,null)}>{time(s.start_ms)}–{time(s.end_ms)} · {((s.end_ms-s.start_ms)/1000).toFixed(1)} s</button>)}</div>{!audio?.silence?.length&&<p className="muted">{audio?"No silence intervals reported.":"Unknown — no direct diagnostics loaded."}</p>}</div>;
 const density=Array.from({length:Math.ceil(duration/15000)},(_,i)=>{const a=i*15000,b=Math.min(duration,a+15000);const n=segments.reduce((sum,s)=>sum+Math.max(0,Math.min(b,s.interval.end_ms)-Math.max(a,s.interval.start_ms))/Math.max(1,s.interval.end_ms-s.interval.start_ms)*s.text.split(/\s+/).length,0);return {t:a,v:n*60000/(b-a)}});
 return <div className="deepdive"><h3>Text deep dive</h3><p className="muted">Content structure and readability evidence. Independent rewrite checks are separate from retention assumptions.</p><div className="deep-grid two"><SignalChart title="Transcript density" description="Words overlapping each 15-second window, scaled to words/min. Includes pauses; differs from active-speech rate." series={[{name:"Transcript density",color:"#268579",points:density}]} duration={duration} unit="words/min"/><SignalChart title="New content terms" description="First appearances of terms in relation windows. High density is a review cue, not proof of overload." series={[{name:"New terms",color:"#7956a5",points:(relations?.cognitive_load.windows??[]).map(w=>({t:w.start_ms,v:w.new_terms}))}]} duration={duration} unit="terms/window"/></div><CandidateFindings pred={pred} duration={duration}/><h4>Independent rewrite checks · Jev</h4><div className="jev-form"><label className="field">Question for the selected passage<input value={question} onChange={e=>setQuestion(e.target.value)}/></label><p className="faint">{selection?time(selection.start_ms)+"–"+time(selection.end_ms):"No passage selected; the whole transcript will be checked in bounded chunks."}</p><button disabled={check.isPending||!question.trim()} onClick={()=>check.mutate()}>{check.isPending?"Checking…":"Ask Jev"}</button>{checkStatus&&<p className="faint">Check status: {checkStatus}</p>}{check.error&&<p className="err">{(check.error as Error).message}</p>}</div><p className="faint">Status: {data?.jev?.status??"unknown"}. {data?.jev?.reason??"A model answer is supporting evidence, not a guarantee that an edit improves retention."}</p><div className="rewrite-grid">{(checked??data?.jev?.decisions??[]).map((d,i)=>{const interval=d.interval??{start_ms:d.start_ms??0,end_ms:d.end_ms??d.start_ms??0};return <article className="rewrite-card" key={i}><div className="deep-heading"><button className="time" onClick={()=>focus(interval,null)}>{time(interval.start_ms)}–{time(interval.end_ms)}</button><span className="pill">{d.decision??d.answer??"Review"}</span></div>{d.question&&<h4>{d.question}</h4>}{d.quote&&<blockquote>{d.quote}</blockquote>}<p className="faint">{d.status??"model judgement"}{typeof d.confidence==="number"?" · selected-choice confidence "+(d.confidence*100).toFixed(0)+"%":""}</p><p><b>Why:</b> {d.explanation??d.reason??"No supported reason supplied."}</p>{d.counter_explanation&&<p><b>Alternative explanation:</b> {d.counter_explanation}</p>}{(d.suggested_rewrite??d.rewrite)&&<p><b>Draft wording — needs review:</b> {d.suggested_rewrite??d.rewrite}</p>}{d.preserve&&<p className="faint"><b>Preserve:</b> {Array.isArray(d.preserve)?d.preserve.join("; "):d.preserve}</p>}</article>})}</div>{!(checked??data?.jev?.decisions)?.length&&<p className="muted">No verified rewrite decisions available. This does not mean every passage is good.</p>}</div>;
}

type Finding={finding_id:string;start_ms:number;end_ms:number;quote:string;mechanism:string;counter_explanation:string;suggestion:string;preserve:string[]|string;severity:string;rule_id:string;measurements?:Record<string,unknown>;earlier_quote?:string};
function CandidateFindings({pred,duration}:{pred?:Prediction;duration:number}){
 const {focus}=usePlayhead(); const analysis=(pred as (Prediction&{analysis?:{findings:Finding[];risk_bins:{start_ms:number;score:number}[]}})|undefined)?.analysis;
 return <><SignalChart title="Transcript review cues" description="Heuristic risk cues from exact passages. These are provisional review candidates, not observed audience drop-off." series={[{name:"Transcript cue score",color:"#c47b32",points:(analysis?.risk_bins??[]).map(b=>({t:b.start_ms,v:b.score}))}]} duration={duration} unit="cue score" min={0}/><h4>Why a passage may need revision</h4><p className="faint">Check the evidence and alternative explanation before accepting an edit. Preserve examples and new information.</p><div className="rewrite-grid">{(analysis?.findings??[]).map(f=><article className="rewrite-card" key={f.finding_id}><div className="deep-heading"><button className="time" onClick={()=>focus({start_ms:f.start_ms,end_ms:f.end_ms},null)}>{time(f.start_ms)}–{time(f.end_ms)}</button><span className="pill">{f.severity} · provisional</span></div><h4>{f.rule_id.replace(/_/g," ")}</h4><blockquote>{f.quote}</blockquote>{f.earlier_quote&&<p><b>Earlier passage:</b> “{f.earlier_quote}”</p>}<Summary data={f.measurements}/><p><b>Reason:</b> {f.mechanism}</p><p><b>Alternative explanation:</b> {f.counter_explanation}</p><p><b>Suggested action:</b> {f.suggestion}</p><p className="faint"><b>Preserve:</b> {Array.isArray(f.preserve)?f.preserve.join("; "):f.preserve}</p></article>)}</div>{!analysis?.findings?.length&&<p className="muted">No text candidates reported by this prediction version.</p>}</>;
}
