(() => {
  'use strict';
  const $ = (s) => document.querySelector(s);
  const $$ = (s) => [...document.querySelectorAll(s)];
  const reduced = window.matchMedia('(prefers-reduced-motion: reduce)');
  let motionPaused = reduced.matches;
  const bg = $('.bg-video');
  const burger = $('.nav__burger'), menu = $('#mobile-menu');
  function closeMenu() { burger.setAttribute('aria-expanded', 'false'); burger.setAttribute('aria-label', 'Open menu'); menu.hidden = true; }
  burger.addEventListener('click', () => { const open = menu.hidden; menu.hidden = !open; burger.setAttribute('aria-expanded', String(open)); burger.setAttribute('aria-label', open ? 'Close menu' : 'Open menu'); });
  menu.addEventListener('click', (e) => { if (e.target.closest('a')) closeMenu(); });
  document.addEventListener('keydown', (e) => { if (e.key === 'Escape') closeMenu(); });
  function syncMotion() { document.body.classList.toggle('motion-paused', motionPaused); $('#motion-toggle').textContent = motionPaused ? 'Resume background motion' : 'Pause background motion'; $('#motion-toggle').setAttribute('aria-pressed', String(motionPaused)); if (motionPaused) bg.pause(); else bg.play().catch(() => {}); }
  $('#motion-toggle').addEventListener('click', () => { motionPaused = !motionPaused; syncMotion(); });
  reduced.addEventListener('change', () => { motionPaused = reduced.matches; syncMotion(); });
  syncMotion();

  const pipelines = {
    video: { stages: [['01','Video','Probe + playback proxy'],['02','Measure','Audio, shots and frames'],['03','Understand','ASR + word alignment'],['04','Reason','Narrative + typed Jev'],['05','Review','Rules, curve and evidence']], description: 'A real video supplies measured timing, waveform and shot evidence. Optional OCR and qualified visual results add coverage; anything missing stays unknown.' },
    audio: { stages: [['01','Recording','Audio + blank playback'],['02','Measure','Loudness, RMS and silence'],['03','Understand','ASR + word alignment'],['04','Reason','Narrative + typed Jev'],['05','Review','Text, voice and scenario']], description: 'The audio path shares transcription and reasoning with video, without inventing visual findings from the blank playback picture.' },
    script: { stages: [['01','Script','Paste / TXT / SRT / VTT'],['02','Parse','Cues or estimated timing'],['03','Understand','Text + E5 embeddings'],['04','Reason','Narrative + typed Jev'],['05','Review','Structure and scenario']], description: 'A script uses subtitle cues or an estimated 150-WPM timeline. There is no measured voice, audio, aligned speech or visual coverage before recording.' }
  };
  function drawPipeline(key) { const p = pipelines[key]; $('#pipeline-flow').replaceChildren(); p.stages.forEach((s, i) => { const step = document.createElement('div'); step.className = 'flow-step'; const icon = document.createElement('span'); icon.className = 'flow-icon'; icon.textContent = s[0]; const title = document.createElement('strong'); title.textContent = s[1]; const detail = document.createElement('small'); detail.textContent = s[2]; step.append(icon, title, detail); $('#pipeline-flow').append(step); if (i < 4) { const link = document.createElement('div'); link.className = 'flow-link'; link.style.setProperty('--delay', `${i * .6}s`); link.setAttribute('aria-hidden', 'true'); $('#pipeline-flow').append(link); } }); $('#pipeline-description').textContent = p.description; $('#pipeline-panel').setAttribute('aria-labelledby', `pipeline-${key}`); $$('[data-pipeline]').forEach(b => b.setAttribute('aria-selected', String(b.dataset.pipeline === key))); }
  $$('[data-pipeline]').forEach(b => b.addEventListener('click', () => drawPipeline(b.dataset.pipeline)));
  drawPipeline('video');

  // Every analytical value below is deliberately seeded for the static showcase.
  // Video files are the supplied samples; these illustrative findings are not live model output.
  const seeds = {
    short: {title:'Jio new device · Hindi Short',kind:'Video · Hindi',duration:24.541,media:'media/jio-short.mp4',source:'https://www.youtube.com/shorts/y7xV8g73n9U',end:.48,phase:.8,caption:'User-supplied 25-second sample · seeded review',transcript:[[0,'दोस्तो, जियो का ये डिवाइस कैसे काम करता है?'],[6,'सिम लगाएं, डिवाइस चालू करें और कनेक्शन जांचें।'],[15,'अब स्क्रीन पर दिखाई गई अगली सेटअप स्टेप को देखें।']],findings:[[2,'Opening promise','Review whether the first sentence gives a concrete reason to stay. A familiar audience may already know the device.','Provisional'],[14,'Setup clarity','Check that the visual setup and spoken step are easy to follow together. This demo has no OCR or visual-AI judgment.','Review candidate'],[21,'Ending transition','Inspect the final seconds before deciding what to trim. Preserve essential setup instructions.','Review candidate']]},
    trailer: {title:'Prahaar · Hindi trailer',kind:'Video · Hindi',duration:184.4,media:'media/prahaar-trailer.mp4',source:'https://www.youtube.com/watch?v=qGbvEhKhaWA',end:.42,phase:2,caption:'User-supplied trailer · seeded review',transcript:[[0,'[Illustrative transcript excerpt — dramatic opening]'],[35,'[Illustrative excerpt — conflict and context]'],[95,'[Illustrative excerpt — title promise develops]'],[165,'[Illustrative excerpt — closing title and release card]']],findings:[[12,'Opening context','A dramatic trailer may intentionally delay exposition. Review the passage in genre context before calling it setup.','Provisional'],[90,'Pace contrast','A change in delivery can be an intentional dramatic beat. Inspect the actual audio before treating a curve dip as a defect.','Review candidate'],[170,'Closing information','Preserve credits, title and required promotional information. A trailer is outside the original educational-video focus.','Review candidate']]},
    education: {title:'Ontology vs metadata · English',kind:'Video · English',duration:286.04,media:'media/education.mp4',source:'https://www.youtube.com/watch?v=ve7AA01vplE',end:.39,phase:1.4,caption:'Earlier local test source · seeded review',transcript:[[0,'[Illustrative excerpt] What is the difference between ontology and metadata?'],[40,'[Illustrative excerpt] A useful distinction needs a concrete example.'],[120,'[Illustrative excerpt] An explanation may reuse terms without being redundant.'],[230,'[Illustrative excerpt] Bring the comparison back to the original question.']],findings:[[35,'Time to substance','Review whether background setup is necessary for the distinction that follows. Preserve prerequisite definitions.','Provisional'],[120,'Repeated terminology','Shared words are not proof of repeated information. Compare the earlier explanation and keep useful elaboration.','Review candidate'],[235,'Title payoff','Check where the promised comparison becomes concrete. A keyword mention is not the same as fulfilment.','Provisional']]},
    audio: {title:'Voice-first · audio excerpt',kind:'Audio · English',duration:40,media:'media/voice-excerpt.wav',source:'https://www.youtube.com/watch?v=ve7AA01vplE',end:.5,phase:2.3,caption:'Playable recording excerpt · seeded delivery data',transcript:[[0,'[Illustrative excerpt] Start with the key question.'],[12,'[Illustrative excerpt] Add a concrete example before the next definition.'],[27,'[Illustrative excerpt] Leave room for the listener to follow.']],findings:[[10,'Relative speaking pace','The full app compares aligned speech rate with the speaker’s own median. This card is an illustrative candidate.','Seeded'],[25,'Quiet pause','A useful pause may help comprehension. No automatic cut is accepted from this demo.','Review candidate']]},
    script: {title:'Before the recording · script',kind:'Script · estimated timing',duration:46,media:null,source:null,end:.44,phase:1,caption:'Seeded original script · estimated timeline',transcript:[[0,'A great review starts with a specific question: what makes this explanation worth finishing?'],[9,'First, give the audience the outcome. Then show a concrete example before introducing the technical detail.'],[22,'If an idea has appeared earlier, preserve the useful example and only remove genuine duplication.'],[35,'Finish with the takeaway that answers the opening question. A suggestion remains a draft until the creator reviews it.']],findings:[[9,'Example placement','Place the worked example near the definition. The script timeline is estimated and does not measure speaking pace.','Provisional'],[22,'Preserve the example','This passage explains a policy. Similar words elsewhere do not make it redundant.','Review candidate']]}
  };
  const esc = (s) => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clock = (t) => `${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;
  let key = 'short', view = 'retention', selected = 0;
  function scenario(s) { const out = [], N = Math.ceil(s.duration); let survival = 1, area = 0; for (let i=0; i<N; i++) { const dt=Math.min(1,s.duration-i); const h0= -Math.log(s.end) * (Math.pow((i+dt)/s.duration,.6)-Math.pow(i/s.duration,.6))/dt; const pressure=Math.exp(.14*Math.sin(i*.18+s.phase)+.08*Math.cos(i*.047)+ (i/s.duration>.72&&i/s.duration<.86?.32:0)); const h=h0*pressure; area+=survival*(-Math.expm1(-h*dt))/h; survival*=Math.exp(-h*dt); out.push({t:i+dt,retention:survival,baseline:Math.exp(Math.log(s.end)*Math.pow((i+dt)/s.duration,.6)),pressure}); } return {points:out,avd:area,apv:100*area/s.duration}; }
  function seek(t) { selected = Math.max(0,Math.min(seeds[key].duration,t)); const media = seeds[key].kind.startsWith('Audio') ? $('#sample-audio') : $('#sample-video'); if (seeds[key].media && Number.isFinite(media.duration)) media.currentTime=Math.min(selected,media.duration); if(view==='retention') renderPanel(); }
  function renderPanel() { const s=seeds[key], m=scenario(s), panel=$('#demo-panel'); panel.setAttribute('aria-labelledby',`tab-${view}`); $$('[data-view]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.view===view)));
    if(view==='retention') { const W=900,H=205,L=35,R=880,T=14,B=180; const x=t=>L+t/s.duration*(R-L), y=v=>B-v*(B-T); const line=(f)=>`M${L},${y(1)} `+m.points.map(p=>`L${x(p.t).toFixed(2)},${y(f(p)).toFixed(2)}`).join(' '); const p=m.points[Math.min(m.points.length-1,Math.floor(selected))]; panel.innerHTML=`<div class="demo-chart-title"><h3>Viewers still watching</h3><span>UNCALIBRATED · ILLUSTRATIVE</span></div><svg class="demo-chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="Seeded retention scenario against an illustrative baseline">${[0,.25,.5,.75,1].map(v=>`<line x1="${L}" x2="${R}" y1="${y(v)}" y2="${y(v)}" stroke="#e8eef4"/><text x="${L-8}" y="${y(v)+4}" text-anchor="end">${v*100}%</text>`).join('')}<path d="${line(p=>p.baseline)}" fill="none" stroke="#b5c7d8" stroke-width="2" stroke-dasharray="5 5"/><path d="${line(p=>p.retention)}" fill="none" stroke="#006cd2" stroke-width="2.5"/><line class="chart-cursor" x1="${x(selected)}" x2="${x(selected)}" y1="${T}" y2="${B}"/>${[0,.25,.5,.75,1].map(v=>`<text x="${x(v*s.duration)}" y="200" text-anchor="${v===0?'start':v===1?'end':'middle'}">${clock(v*s.duration)}</text>`).join('')}</svg><div class="chart-legend"><span>Illustrative scenario</span><span>Assumed baseline</span></div><div class="demo-inspect"><span>${clock(selected)} · ${(selected === 0 ? 100 : p.retention*100).toFixed(1)}% still watching · ${p.pressure.toFixed(2)}× seeded departure pressure</span><input type="range" min="0" max="${s.duration}" step=".1" value="${selected}" aria-label="Inspect demo timestamp"></div><p class="chart-note">Undulations belong in departure pressure and changing slopes. Survival remains non-increasing. This seeded trace is a demonstration of the display, not an analytical result for the sample.</p>`; panel.querySelector('input').addEventListener('input',e=>{const value=+e.target.value;selected=value;const media=s.kind.startsWith('Audio')?$('#sample-audio'):$('#sample-video');if(s.media&&Number.isFinite(media.duration)) media.currentTime=value; const point=m.points[Math.min(m.points.length-1,Math.floor(value))];panel.querySelector('.demo-inspect span').textContent=`${clock(value)} · ${(value === 0 ? 100 : point.retention*100).toFixed(1)}% still watching · ${point.pressure.toFixed(2)}× seeded departure pressure`; const cursor=panel.querySelector('.chart-cursor');cursor.setAttribute('x1',x(value));cursor.setAttribute('x2',x(value));}); }
    else if(view==='findings') { panel.innerHTML=s.findings.map(f=>`<article class="finding-demo"><button data-time="${f[0]}">${clock(f[0])} ↗</button><div><h4>${esc(f[1])}</h4><p>${esc(f[2])}</p></div><small>${esc(f[3])}</small></article>`).join(''); }
    else if(view==='transcript') { panel.innerHTML=`<p class="chart-note">${s.kind.startsWith('Script')?'Original seeded script with estimated timings.':'Illustrative text snippets — not an authoritative transcription of the sample.'}</p><div class="transcript-demo">${s.transcript.map(t=>`<div class="transcript-line"><button data-time="${t[0]}">${clock(t[0])}</button><p>${esc(t[1])}</p></div>`).join('')}</div>`; }
    else { panel.innerHTML=`<div class="jev-demo"><article class="jev-decision"><span>SEEDED CHOICE / 82% CONFIDENCE</span><h4>Keep the concrete example.</h4><div class="jev-meter"><i style="width:82%"></i></div><p>The passage adds a useful example. The full pipeline validates all four option probabilities and retains context. This is a seeded illustration of a keep route.</p></article><article class="jev-decision"><span>SEEDED CHOICE / 54% CONFIDENCE</span><h4>Route to review.</h4><div class="jev-meter"><i style="width:54%"></i></div><p>The model leaned toward shortening, but confidence is below 65%. Keep the source until review confirms actual earlier duplication. Confidence is not editorial correctness.</p></article></div><p class="chart-note">Real Jev is integrated in the local pipeline and its on-demand route. This static showcase makes no TypeSafe or Cerebras request, generates no new judgment, and applies no edits.</p>`; }
    panel.querySelectorAll('[data-time]').forEach(b=>b.addEventListener('click',()=>seek(+b.dataset.time)));
  }
  function loadSample() { const s=seeds[key], m=scenario(s); selected=0; $('#demo-apv').textContent=`${m.apv.toFixed(0)}%`;$('#demo-avd').textContent=clock(m.avd);$('#source-tag').textContent=s.kind;$('#sample-caption').textContent=s.caption;const video=$('#sample-video'),audio=$('#sample-audio'),script=$('#sample-script');video.pause();audio.pause();video.hidden=!s.media||s.kind.startsWith('Audio');audio.hidden=!s.kind.startsWith('Audio');script.hidden=!!s.media;video.removeAttribute('src');audio.removeAttribute('src');if(s.media){const target=s.kind.startsWith('Audio')?audio:video;target.src=s.media;target.load();}else script.textContent=s.transcript.map(t=>t[1]).join('\n\n'); $('#source-link').hidden=!s.source;if(s.source)$('#source-link').href=s.source;renderPanel(); }
  $('#sample-picker').addEventListener('change', e=>{key=e.target.value;loadSample();});
  $$('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;renderPanel();}));
  $('#export-demo').addEventListener('click',()=>{const s=seeds[key];const blob=new Blob([JSON.stringify({label:'Seeded static demonstration. Not audience data or live AI analysis.',project:s.title,scenario:scenario(s),illustrative_findings:s.findings},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`epoch-demo-${key}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
  loadSample();

  // A small self-contained WebGL landscape shader: no library, telemetry or asset request.
  const canvas=$('#footer-shader');
  const gl=canvas.getContext('webgl',{alpha:false,antialias:false,powerPreference:'low-power'});
  if(!gl)return;
  const vertex='attribute vec2 a;void main(){gl_Position=vec4(a,0.,1.);}';
  const fragment=`precision mediump float;uniform vec2 resolution;uniform float time;
    float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}
    float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1.,0.)),f.x),mix(hash(i+vec2(0.,1.)),hash(i+vec2(1.,1.)),f.x),f.y);}
    float fbm(vec2 p){float v=0.,a=.5;for(int i=0;i<4;i++){v+=a*noise(p);p=p*2.03+3.1;a*=.5;}return v;}
    void main(){vec2 uv=gl_FragCoord.xy/resolution;vec2 p=vec2(uv.x*2.2,uv.y);float t=time*.025;vec3 c=mix(vec3(.025,.06,.105),vec3(.14,.25,.37),uv.y);float glow=exp(-length((uv-vec2(.76,.31))*vec2(1.3,1.8))*4.);c+=vec3(.39,.19,.09)*glow*.58;for(int i=0;i<6;i++){float layer=float(i);float ridge=.08+layer*.082+.09*sin(p.x*2.8+layer*.7+t)+.13*fbm(vec2(p.x*2.+layer*4.,t*.4+layer));float edge=1.-smoothstep(ridge-.008,ridge+.008,uv.y);vec3 navy=mix(vec3(.025,.065,.11),vec3(.12,.2,.3),layer/6.);float gold=pow(max(0.,sin(p.x*3.2+layer*1.1)),6.);navy+=vec3(.44,.20,.08)*gold*.3;navy+=fbm(p*8.+layer)*.025;c=mix(c,navy,edge*.88);}c+=((hash(gl_FragCoord.xy)-.5)*.008);gl_FragColor=vec4(c,1.);}`;
  function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))return null;return s;}
  const vs=shader(gl.VERTEX_SHADER,vertex),fs=shader(gl.FRAGMENT_SHADER,fragment);if(!vs||!fs)return;
  const program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))return;gl.useProgram(program);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const attr=gl.getAttribLocation(program,'a');gl.enableVertexAttribArray(attr);gl.vertexAttribPointer(attr,2,gl.FLOAT,false,0,0);const rt=gl.getUniformLocation(program,'resolution'),tt=gl.getUniformLocation(program,'time');let visible=false,elapsed=0,last=0;
  function resize(){const ratio=Math.min(window.devicePixelRatio||1,1.5);const r=canvas.getBoundingClientRect();canvas.width=Math.round(r.width*ratio);canvas.height=Math.round(r.height*ratio);gl.viewport(0,0,canvas.width,canvas.height);gl.uniform2f(rt,canvas.width,canvas.height);gl.uniform1f(tt,elapsed);gl.drawArrays(gl.TRIANGLES,0,6);}
  new ResizeObserver(resize).observe(canvas);
  new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;}).observe(canvas);
  document.addEventListener('visibilitychange',()=>{last=0;});
  function frame(now){if(visible&&!document.hidden&&!motionPaused){if(last)elapsed+=Math.min(.1,(now-last)/1000);gl.uniform1f(tt,elapsed);gl.drawArrays(gl.TRIANGLES,0,6);}last=now;requestAnimationFrame(frame);}
  resize();requestAnimationFrame(frame);
})();
